color-placeholders: false

refresh-intervals:
  default: 1000
  "%vault_rank%": 1000

expansions-config:
  replace: # %replacements_<placeholder type>_<replacement name>_<placeholder>%
    "%vault_rank%":
      "color": # %replacements_player_color_vault_rank%
        "admin": "&cAdmin"
        "else": "&7%value%"
      "chatcolor": # %replacements_player_chatcolor_vault_rank%
        "admin": "&c"
        "else": "&7"